apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: protocol
      value: amqp
    - name: hostname
      value: localhost
    - name: username
      value: user
    - name: password
      value: ThisIsAPassword
    - name: durable
      value: true
    - name: deletedWhenUnused
      value: false
    - name: autoAck
      value: false
    - name: reconnectWait
      value: 0
    - name: concurrency
      value: parallel
    - name: exchangeKind
      value: fanout
