@MessagePublisher_HostAddress = http://localhost:5216

POST {{MessagePublisher_HostAddress}}/
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "message": "Hello, World!"
}


###
